name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Run the tests
      run: yarn test

    - name: Build the app
      run: yarn build

    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        args: "-avzr --delete deploy@fdgt.dev:/var/www/fdgt/"
